import React, { useEffect } from "react";
import { RandomUser } from "../interfaces/RandomUser.interface";

// Generated by https://quicktype.io


const URL_RANDOM_USER = "https://randomuser.me/api/?results=20";

function ListChats(
  props: {
    setSelectedChat: (chat: RandomUser) => void;
  }
) {
  const [searchTerm, setSearchTerm] = React.useState("");
  const [users, setUsers] = React.useState<RandomUser[]>([]);
  const [allUsers, setAllUsers] = React.useState<RandomUser[]>([]);
  

  useEffect(() => {
    const fetchData = async () => {
      const response = await fetch(URL_RANDOM_USER);
      const data = await response.json();
      setAllUsers(data.results);
      setUsers(data.results);
    };
    fetchData();
  }, []);

  useEffect(() => {
    setUsers(
      allUsers.filter(
        (user) =>
          user.name.first.toLowerCase().includes(searchTerm.toLowerCase()) ||
          user.name.last.toLowerCase().includes(searchTerm.toLowerCase())
      )
    );
  }, [searchTerm]);

  return (
    <div className="border-r border-sky-700">
      <header>
        <input
          className="text-black bg-gray-100 rounded p-2"
          placeholder="Search"
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          type="search"
          name="search-chats"
          id="search-chats"
        />
      </header>
      <main>
        <div
          className="overflow-scroll h-5/6 p-4 bg-gray-900  rounded"
          style={{ height: "calc(95vh)", width: "100%" }}
        >
          {users.map((n, idx) => {
            return (
              <article
                key={idx}
                className="flex gap-4 items-center mb-6 cursor-pointer"
                onClick={() => props.setSelectedChat(n)}
              >
                <picture>
                  <img
                    className="rounded-full w-8 h-8"
                    src={n.picture.large}
                    alt="avatar"
                  />
                </picture>
                <p className="font-bold">
                  {n.name.first} {n.name.last}
                </p>
              </article>
            );
          })}
        </div>
      </main>
    </div>
  );
}

export default ListChats;
